project:
  type: website 
  output-dir: docs

website:
  title: "Leo Liu"
  search: false
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer: 
     background: dark
     center: 
      - text: "Copyright 2024, Yuanyi (Leo) Liu" 

format:
  html:
    theme: cosmo
    grid:
      margin-width: 0px
    css: styles.css
    toc: true

editor: visual

